<script id="articles-page-article-table-row-template" type="text/template">
    <td class="title"><%- name %></td>
    <td class="description"><%- default_unit_price %> &euro; / <%- quantityUnitCategory.value %></td>
    <td>
        <div class="right">
            <% if (active) { %>
            <i class="fas fa-check"></i>
            <% } else { %>
            <i class="fas fa-check fa-disabled"></i>
            <% } %>
        </div>
    </td>
</script>