<script id="output-page-task-table-row-template" type="text/template">
    <td>
        <div><%- date.dateFormat('d') %> <%- polyglot.t('date.month.' + date.dateFormat('M').toLowerCase()) %></div>
        <div class="description"><%- time.substring(0, 5) %></div>
    </td>
    <td>
        <div><%- category.value %></div>
    </td>
    <td>
        <div class="description right">
            <% if (durationByMwu != '00:00:00') { %>
            <div><%- durationByMwu.substring(0, 5) %> / <i class="fas fa-user fa-fw"></i></div>
            <% } %>
            <% if (photoCount > 0) { %>
            <div><%- photoCount %> <i class="fas fa-image fa-fw"></i></div>
            <% } %>
        </div>
    </td>
</script>