<script id="outputs-page-output-table-row-template" type="text/template">
    <td>
        <div><%- task.date.dateFormat('d') %> <%- polyglot.t('date.month.' + task.date.dateFormat('M').toLowerCase()) %></div>
        <div class="description"><%- task.time.substring(0, 5) %></div>
    </td>
    <td>
        <div>
            <%- article.name %>
        </div>
        <div class="description">
            <% if (variety) { %>
            <span><%- plant.name %> <%- variety.name %></span>
            <% } else { %>
            <span><%- polyglot.t('model.field.variety_id.null').toLowerCase() %></span>
            <% } %>
        </div>
    </td>
    <td>
        <div class="right"><%- quantity %> <%- quantity_unit.value %></div>
    </td>
</script>