<script id="task-page-seedling-table-row-template" type="text/template">
    <td>
        <i class="fas fa-map-pin fa-fw"></i>
    </td>
    <td>
        <div>
            <%- polyglot.t('model.name.seedling') %> <%- category.value.toLowerCase() %>
            <% if (nursery) { %>
            <span> - <%- polyglot.t('model.field.nursery') %></span>
            <% } %>
        </div>
        <div class="description">
            <div>
                <%- organization ? organization.name : entity.name %> -
                <%- variety ? plant.name + ' ' + variety.name : article.name %>
            </div>
            <div><%- density %> <%- density_unit.value %> / <%- area_unit.value %> x <%- area %> <%- area_unit.value %></div>
        </div>
    </td>
    <td>
        <div class="right nowrap">
            <% if (density_unit.key == 'g') { %>
            <%- (density * area).toFixed(2) %> <%- density_unit.value %>
            <% } else { %>
            <%- density * area %> <%- density_unit.value %>
            <% } %>
        </div>
    </td>
</script>