<script id="task-page-model-template" type="text/template">
    <table>
        <tr>
            <td>
                <div class="label"><%- polyglot.t('model.field.date') %></div>
            </td>
            <td>
                <div class="value">
                    <%- date.dateFormat('d') %>
                    <%- polyglot.t('date.month.' + date.dateFormat('M').toLowerCase()) %>
                    <%- time.substring(0, 5) %>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="label"><%- polyglot.t('model.field.done') %></div>
            </td>
            <td>
                <div class="value"><%- polyglot.t('model.field.done.' + done) %></div>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div class="description">
                    <% if (description) { %><%= description.nl2br() %><% } %>
                </div>
            </td>
        </tr>
    </table>
</script>