<script id="task-page-planting-table-row-template" type="text/template">
    <td>
        <i class="fas fa-screwdriver"></i>
    </td>
    <td>
        <div>
            <%- polyglot.t('model.name.planting') %> <%- category.value.toLowerCase() %>
        </div>
        <div class="description">
            <div><%- plant.name %> <%- variety.name %></div>
            <div><%- intra_row_spacing %> cm x <%- inter_row_spacing %> cm - <%- area %> m²</div>
        </div>
    </td>
    <td>
        <div class="right">
            <%- Math.round((100 / intra_row_spacing) * (100 / inter_row_spacing) * area) %> plant(s)
        </div>
    </td>
</script>