<script id="task-page-seedling-table-row-template" type="text/template">
    <td>
        <i class="fas fa-seedling"></i>
    </td>
    <td>
        <div>
            <%- polyglot.t('model.name.seedling') %> <%- category.value.toLowerCase() %>
            <% if (nursery) { %>
            <span><%- polyglot.t('model.field.nursery') %></span>
            <% } %>
        </div>
        <div class="description">
            <div><%- plant.name %> <%- variety.name %></div>
            <div><%- density %> <%- density_unit.value %> / <%- area_unit.value %> x <%- area %> <%- area_unit.value %></div>
        </div>
    </td>
    <td>
        <div class="right">
            <%- (density * area).toFixed(2) %> <%- density_unit.value %>
        </div>
    </td>
</script>