<script id="task-page-output-table-row-template" type="text/template">
    <td>
        <i class="fas fa-dolly"></i>
    </td>
    <td>
        <div>
            <%- article.name %>
        </div>
    </td>
    <td>
        <div>
            <% if (variety) { %>
            <span><%- variety.name %></span>
            <% } else { %>
            <span><%- polyglot.t('model.field.variety_id.null').toLowerCase() %></span>
            <% } %>
        </div>
    </td>
    <td>
        <div class="right"><%- quantity %> <%- quantity_unit.value %></div>
    </td>
</script>