<script id="task-page-seeding-table-row-template" type="text/template">
    <td>
        <i class="fas fa-seedling"></i>
    </td>
    <td>
        <div><%- polyglot.t('model.name.seeding') %> <%- category.value.toLowerCase() %></div>
        <% if (nursery) { %>
        <div class="description"><%- polyglot.t('model.field.nursery') %></div>
        <% } %>
        <div class="description"><%- plant.name %> <%- variety.name %></div>
    </td>
    <td>
        <div class="description right"><%- density %> <%- density_unit.value %> / <%- area_unit.value %></div>
        <div class="description right"><%- area %> <%- area_unit.value %></div>
    </td>
</script>