<script id="tasks-page-task-table-row-template" type="text/template">
    <td>
        <% if (status == 'planned') { %><i class="fa fa-calendar"></i><% } %>
        <% if (status == 'in_progress') { %><i class="fa fa-clock-o"></i><% } %>
        <% if (status == 'complete') { %><i class="fa fa-check"></i><% } %>
    </td>
    <td>
        <div>
            <% if (provider) { %><i class="fa fa-copyright"></i><% } %>
            <% if (crop) { %><i class="fa fa-crop"></i><% } %>
            <% if (pos) { %><i class="fa fa-truck"></i><% } %>
            <%- category.name %>
        </div>
        <div class="description">
        <% if (provider) { %><%- provider.name %><% } %>
        <% if (crop) { %><%- variety.common_name %><% } %>
        <% if (pos) { %><%- pos.name %><% } %>
        </div>
    </td>
    <td class="description date"><%- planned_date %></td>
</script>