<script id="crop-page-model-body-template" type="text/template">
    <table>
        <tr>
            <td class="image" style="background-image: url('/img/species/species-<%- species.id %>.jpg')"></td>
            <td class="content">
                <div class="title">
                    <i class="fa fa-pagelines"></i> <%- variety.common_name %>
                </div>
                <% if (description) { %>
                <div class="description"><%= description.replace(/[\r\n?]/g, '<br />') %></div>
                <% } %>
            </td>
            <td class="content">
                <div class="title">
                    <% if (status == 'planned') { %><i class="fa fa-calendar"></i><% } %>
                    <% if (status == 'in_progress') { %><i class="fa fa-clock-o"></i><% } %>
                    <% if (status == 'complete') { %><i class="fa fa-check"></i><% } %>
                </div>
            </td>
        </tr>
    </table>
</script>