<script id="crop-page-snapshot-table-row-template" type="text/template">
    <td class="description"><%- date %></td>
    <td class="description"><%- category.name %> <%- type %></td>
    <td class="description"><%- min %>-<%- max %> <%- unit %></td>
    <td class="description">
        <% if (photoNum > 0) { %><div><i class="fa fa-camera-retro"></i> <%- photoNum %></div><% } %>
    </td>
</script>