<script id="crop-page-task-table-row-template" type="text/template">
    <td>
        <% if (status == 'planned') { %><i class="fa fa-calendar"></i><% } %>
        <% if (status == 'in_progress') { %><i class="fa fa-clock-o"></i><% } %>
        <% if (status == 'complete') { %><i class="fa fa-check"></i><% } %>
    </td>
    <td>
        <div><%- category.name %></div>
        <div class="description"><%- planned_date %></div>
    </td>
    <td class="description"><%- duration %> h/m</td>
    <td class="description">
        <% if (inputNum > 0) { %><div><i class="fa fa-sign-in"></i> <%- inputNum %></div><% } %>
        <% if (outputNum > 0) { %><div><i class="fa fa-sign-out"></i> <%- outputNum %></div><% } %>
        <% if (photoNum > 0) { %><div><i class="fa fa-camera-retro"></i> <%- photoNum %></div><% } %>
    </td>
</script>