<script id="snapshot-page-model-body-template" type="text/template">
    <table>
        <tr>
            <td class="content">
                <div class="title">
                    <%- category.name %> <%- type %>
                </div>
                <div class="description">
                    <div><%- date %> - <%- min %>-<%- max %> <%- unit %></div>
                    <% if (description) { %>
                    <div><%= description.replace(/[\r\n?]/g, '<br />') %></div>
                    <% } %>
                </div>
            </td>
        </tr>
    </table>
</script>