<script id="entity-page-model-template" type="text/template">
    <table>
        <tr>
            <td>
                <div class="label"><%- polyglot.t('model.field.farm') %></div>
            </td>
            <td>
                <div class="value"><%- name %></div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="label"><%- polyglot.t('model.field.number') %></div>
            </td>
            <td>
                <div class="value"><%- number %></div>
            </td>
        </tr>
    </table>
</script>