<script id="crops-page-crop-table-row-template" type="text/template">
    <td class="image" style="background-image: url('/img/species/species-<%- species.id %>.jpg')"></td>
    <td>
        <div class="title">
            <span>
                <% if (status == 'planned') { %><i class="fa fa-calendar"></i><% } %>
                <% if (status == 'in_progress') { %><i class="fa fa-clock-o"></i><% } %>
                <% if (status == 'complete') { %><i class="fa fa-check"></i><% } %>
            </span>
            <%- variety.common_name %>
        </div>
        <div class="description">
            <% _.each(implantations, function (implantation) { %>
            <div>- <%- implantation.block.name %> <%- implantation.bed.name %></div>
            <% }); %>
        </div>
    </td>
    <td class="description">
        <% if (implantationNum > 0) { %><div><i class="fa fa-map-marker"></i> <%- implantationNum %></div><% } %>
        <% if (taskNum > 0) { %><div><i class="fa fa-tasks"></i> <%- taskNum %></div><% } %>
        <% if (snapshotNum > 0) { %><div><i class="fa fa-tags"></i> <%- snapshotNum %></div><% } %>
    </td>
</script>