<script id="product-page-model-body-template" type="text/template">
    <table>
        <tr>
            <% if (variety) { %>
            <td class="image" style="background-image: url('/img/species/species-<%- species.id %>.jpg')"></td>
            <% } %>
            <td class="content">
                <div class="title"><%- category.name %> <%- name %></div>
                <table class="description">
                    <tr><td>Provider:</td><td><%- provider.name %></td></tr>
                    <% if (variety) { %>
                    <tr><td>Variety:</td><td><%- variety.common_name %></td></tr>
                    <% } %>
                    <tr><td>Reference:</td><td><%- reference %></td></tr>
                    <tr><td>Unit:</td><td><%- quantity_unit %></td></tr>
                </table>
            </td>
        </tr>
    </table>
</script>