<script id="task-page-model-body-template" type="text/template">
    <table>
        <tr>
            <% if (crop) { %>
            <td class="image" style="background-image: url('/img/species/species-<%- species.id %>.jpg')"></td>
            <% } %>
            <td class="content">
                <div class="title">
                    <% if (provider) { %><i class="fa fa-copyright"></i><% } %>
                    <% if (crop) { %><i class="fa fa-crop"></i><% } %>
                    <% if (pos) { %><i class="fa fa-truck"></i><% } %>
                    <%- category.name %>
                </div>
                <div class="description">
                <% if (provider) { %><%- provider.name %><% } %>
                <% if (crop) { %><%- variety.common_name %><% } %>
                <% if (pos) { %><%- pos.name %><% } %>
                </div>
                <div class="description"><%- planned_date %></div>
                <% if (description) { %>
                <div class="description"><%= description.replace(/[\r\n?]/g, '<br />') %></div>
                <% } %>
            </td>
            <td class="content">
                <div class="title">
                    <% if (status == 'planned') { %><i class="fa fa-calendar"></i><% } %>
                    <% if (status == 'in_progress') { %><i class="fa fa-clock-o"></i><% } %>
                    <% if (status == 'complete') { %><i class="fa fa-check"></i><% } %>
                </div>
            </td>
        </tr>
    </table>
</script>