<script id="flow-page-flow-table-row-template" type="text/template">
    <td class="description"><%- date %></td>
    <td>
        <div class="title">
        <% if (type == 'input') { %>
        <i class="fa fa-sign-in"></i>
        <% } else { %>
        <i class="fa fa-sign-out"></i>
        <% } %>
        <% if (provider) { %><%- taskCategory.name %> <%- provider.name %><% } %>
        <% if (crop) { %><%- taskCategory.name %><% } %>
        <% if (pos) { %><%- taskCategory.name %> <%- pos.name %><% } %>
        </div>
        <div class="description">
            <div><%- product.name %></div>
            <div>
                <span><%- productCategory.name %>: <%- quantity %> <%- product.quantity_unit %>, </span>
                <span>Lot: <% if (flow) { %><%- flow.lot %><% } else { %><%- lot %><% } %></span>
            </div>
        </div>
    </td>
</script>